name: Code quality check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run unit tests and ESLint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Run unit tests and build
        run: |
           npm ci
           npm run test:ci
      - name: Run ESLint checks
        run: npm run eslint